#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 07, 2021 05:56:02 PM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import delivery_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = topLevel (root)
    delivery_support.init(root, top)
    root.mainloop()

w = None
def create_topLevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_topLevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = topLevel (w)
    delivery_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_topLevel():
    global w
    w.destroy()
    w = None

class topLevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("208x145+474+241")
        top.minsize(120, 1)
        top.maxsize(5764, 1061)
        top.resizable(1,  1)
        top.title("Planter Price Calculator")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.deliveryFrame = tk.LabelFrame(top)
        self.deliveryFrame.place(relx=0.048, rely=0.0, relheight=0.966
                , relwidth=0.913)
        self.deliveryFrame.configure(relief='groove')
        self.deliveryFrame.configure(foreground="black")
        self.deliveryFrame.configure(text='''Delivery''')
        self.deliveryFrame.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.deliveryFrame)
        self.Label1.place(relx=0.053, rely=0.143, height=41, width=174
                , bordermode='ignore')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(relief="sunken")
        self.Label1.configure(text='''Enter Postcode To Calculate''')

        self.targetPostcodeEntry = tk.Entry(self.deliveryFrame)
        self.targetPostcodeEntry.place(relx=0.368, rely=0.5, height=20
                , relwidth=0.6, bordermode='ignore')
        self.targetPostcodeEntry.configure(background="white")
        self.targetPostcodeEntry.configure(disabledforeground="#a3a3a3")
        self.targetPostcodeEntry.configure(font="TkFixedFont")
        self.targetPostcodeEntry.configure(foreground="#000000")
        self.targetPostcodeEntry.configure(insertbackground="black")

        self.targerPostcodeLabel = tk.Label(self.deliveryFrame)
        self.targerPostcodeLabel.place(relx=0.053, rely=0.5, height=22, width=54
                , bordermode='ignore')
        self.targerPostcodeLabel.configure(background="#d9d9d9")
        self.targerPostcodeLabel.configure(disabledforeground="#a3a3a3")
        self.targerPostcodeLabel.configure(foreground="#000000")
        self.targerPostcodeLabel.configure(text='''Postcode''')

        self.calculateButton = tk.Button(self.deliveryFrame)
        self.calculateButton.place(relx=0.316, rely=0.714, height=24, width=67
                , bordermode='ignore')
        self.calculateButton.configure(activebackground="#ececec")
        self.calculateButton.configure(activeforeground="#000000")
        self.calculateButton.configure(background="#d9d9d9")
        self.calculateButton.configure(disabledforeground="#a3a3a3")
        self.calculateButton.configure(foreground="#000000")
        self.calculateButton.configure(highlightbackground="#d9d9d9")
        self.calculateButton.configure(highlightcolor="black")
        self.calculateButton.configure(pady="0")
        self.calculateButton.configure(text='''Calculate''')

if __name__ == '__main__':
    vp_start_gui()





